name: Build Android APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev libssl-dev python3-pip \
          zip unzip openjdk-17-jdk libncurses5 libncursesw5 zlib1g-dev \
          libjpeg-dev libfreetype6-dev pkg-config ant
          
          pip install --upgrade pip
          pip install "cython<3.0" buildozer
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build with Buildozer
        run: |
          # میموری بڑھانے کے لیے تاکہ لارج سائز کا مسئلہ نہ آئے
          export GRADLE_OPTS="-Xmx2048m"
          export APP_ANDROID_SDK=$ANDROID_HOME
          yes | buildozer android debug --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Secret-Vault-Final-APK
          path: bin/*.apk
