name: Build Android APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev libssl-dev python3-pip
          pip install --upgrade pip
          pip install "cython<3.0" buildozer
          # یہ راستہ (Path) دوبارہ سیٹ کر رہا ہوں تاکہ پرانا مسئلہ نہ آئے
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build with Buildozer
        run: |
          # یہاں ہم ڈیپ سیک والا طریقہ (yes | اور --verbose) استعمال کر رہے ہیں
          # تاکہ AIDL والا لائسنس خود بخود ایکسیپٹ ہو جائے
          yes | buildozer android debug --verbose
