name: Build Android APK
on: [push, pull_request]

jobs:
  build:
    # یہاں ہم نے ورژن 22.04 کر دیا ہے جو زیادہ سٹیبل ہے
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install basic tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev libssl-dev python3-pip zip unzip openjdk-17-jdk
          pip install --upgrade pip
          pip install "cython<3.0" buildozer
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build with Buildozer
        run: |
          # اب بلڈوزر خود اپنی ضرورت کی چیزیں ڈاؤن لوڈ کر لے گا
          yes | buildozer android debug --verbose
          
